# example for reference: https://github.com/marketplace/actions/python-coverage-comment
name: Post coverage comment

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

jobs:
  test:
    name: Display test coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      # DO NOT run actions/checkout@v2 here, for security reasons
      # For details, refer to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
      - name: Post Python Coverage Comment
        uses: ewjoachim/python-coverage-comment-action@v3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          # Update these if the default values have been changed:
          # COMMENT_ARTIFACT_NAME: python-coverage-comment-action
          # COMMENT_FILENAME: python-coverage-comment-action.txt
