name: Deploy Cloud Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.workflows.yaml"

jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Get workflow information
        id: get-workflow-info
        run: |
          # first line of file contains the workflow name as 'name="workflow-name"'
          WORKFLOW_NAME=$(head -n 1 data-pipeline.workflows.yaml | cut -d'"' -f2)
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          # second line of the file contains the workflow description as 'description="workflow-description"'
          WORKFLOW_DESCRIPTION=$(head -n 2 data-pipeline.workflows.yaml | tail -n 1 | cut -d'"' -f2)
          echo "WORKFLOW_DESCRIPTION=$WORKFLOW_DESCRIPTION" >> $GITHUB_ENV

      - name: gcloud workflows deploy
        run: |
          gcloud workflows deploy ${{ steps.get-workflow-info.outputs.WORKFLOW_NAME }} \
          --location us-west1 \
          --source data-pipeline.workflows.yaml \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --description "${{ steps.get-workflow-info.outputs.WORKFLOW_DESCRIPTION }}" \
          --labels "commit-sha=${{ github.sha }}" \
          --service-account workflows@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com



