name: Deploy Cloud Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data-pipeline.workflows.yaml"

jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: gcloud workflows deploy
        run: |
          gcloud workflows deploy data-pipeline \
          --location us-west1 \
          --source data-pipeline.workflows.yaml \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --description "Runs the HTTPArchive data pipeline" \
          --labels "commit-sha=${{ github.sha }}" \
          --service-account workflows@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
